name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build blackjack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make libncurses-dev

      - name: Build project
        run: make

      - name: Check binary exists
        run: |
          test -f bin/blackjack
