name: Format Check

on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22
          sudo ln -sf /usr/bin/clang-format-22 /usr/bin/clang-format
        
      - name: Show clang-format version
        run: clang-format --version
  
      - name: Check formatting
        run: make format-check
